version: '3'
services:
    opinion-retrieval:
        container_name: opinion_retrieval
        image: "opinion_retrieval:5.2.0"
        ports:
            - "8888:8888"
            - "5000:5000"
        volumes:
            - .:/app
        command: bash
        stdin_open: true
        tty: true
        links:
            - rabbitmq
    rabbitmq:
        container_name: rabbitmq
        image: "rabbitmq:3"
